=== Tiagoferrao6/L2Journey/dist/game/data/xsd/fake_shops.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="shops">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="fakeshop" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="customitem" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="id" type="xs:integer" use="required"/>
									<xs:attribute name="count" type="xs:integer" use="required"/>
									<xs:attribute name="price" type="xs:long" use="required"/>
									<xs:attribute name="minEnchant" type="xs:integer" use="optional"/>
									<xs:attribute name="maxEnchant" type="xs:integer" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required"/>
						<xs:attribute name="title" type="xs:string" use="required"/>
						<xs:attribute name="classId" type="xs:integer" use="required"/>
						<xs:attribute name="level" type="xs:integer" use="required"/>
						<xs:attribute name="x" type="xs:integer" use="required"/>
						<xs:attribute name="y" type="xs:integer" use="required"/>
						<xs:attribute name="z" type="xs:integer" use="required"/>
						<xs:attribute name="heading" type="xs:integer" use="required"/>
						<xs:attribute name="city" type="xs:string" use="required"/>
						<xs:attribute name="type" type="xs:string" use="required"/>
						<xs:attribute name="category" type="xs:string" use="required"/>
						<xs:attribute name="updateInterval" type="xs:integer" use="required"/>
						<xs:attribute name="maxItems" type="xs:integer" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Tiagoferrao6/L2Journey/dist/game/data/fakeplayers/fake_shops.xml
<?xml version="1.0" encoding="UTF-8"?>
<shops xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/fake_shops.xsd">
	<!-- =================================================================== -->
	<!-- 1. GLUDIO TOWN (Mercado de Transição C e D-Grade - 15 Lojas)        -->
	<!-- =================================================================== -->
	<fakeshop name="Gimli" title="Mats Basicos D (Steel/Cokes)" classId="53" level="40" x="-14228" y="123445" z="-3115" heading="16384" city="Gludio" type="SELL" category="MATERIALS" updateInterval="30" maxItems="5" />
	<fakeshop name="Thorin" title="Shots &amp; Potions D" classId="56" level="52" x="-14180" y="123480" z="-3115" heading="32768" city="Gludio" type="SELL" category="SUPPLIES" updateInterval="30" maxItems="5" />
	<fakeshop name="Durin" title="Armas e Armaduras D" classId="53" level="40" x="-14130" y="123520" z="-3115" heading="49152" city="Gludio" type="SELL" category="ITEMS" updateInterval="30" maxItems="4" />
	<fakeshop name="Balin" title="Enchants D &amp; Cristais Top D" classId="54" level="35" x="-14260" y="123550" z="-3115" heading="0" city="Gludio" type="SELL" category="SUPPLIES" updateInterval="30" maxItems="4">
		<customitem id="951" count="2" price="550000" /> <!-- Scroll: Enchant Weapon D -->
		<customitem id="952" count="5" price="95000" />  <!-- Scroll: Enchant Armor D -->
		<customitem id="1458" count="100" price="520" />  <!-- Crystal D -->
		<customitem id="2130" count="20" price="3500" />  <!-- Gemstone D -->
	</fakeshop>
	<fakeshop name="Dwalin" title="Shots D &amp; BSS D-Grade" classId="55" level="35" x="-14310" y="123500" z="-3115" heading="16384" city="Gludio" type="SELL" category="SUPPLIES" updateInterval="30" maxItems="3">
		<customitem id="1835" count="3000" price="10" /> <!-- Soulshot D -->
		<customitem id="3947" count="1500" price="25" /> <!-- Spiritshot D -->
		<customitem id="3948" count="1000" price="40" /> <!-- Blessed Spiritshot D -->
	</fakeshop>
	<fakeshop name="Fili" title="Potions D &amp; Res/SoE" classId="9" level="40" x="-14350" y="123445" z="-3115" heading="32768" city="Gludio" type="SELL" category="SUPPLIES" updateInterval="30" maxItems="5">
		<customitem id="1539" count="50" price="1800" />
		<customitem id="1540" count="15" price="10000" />
		<customitem id="734" count="15" price="3000" />
		<customitem id="737" count="10" price="500" />
		<customitem id="738" count="5" price="2800" />
	</fakeshop>
	<fakeshop name="Kili" title="Arcos D &amp; Bone Arrows" classId="22" level="35" x="-14228" y="123380" z="-3115" heading="49152" city="Gludio" type="SELL" category="ITEMS" updateInterval="30" maxItems="3">
		<customitem id="277" count="1" price="1600000" />
		<customitem id="284" count="1" price="1650000" />
		<customitem id="1342" count="2000" price="5" />
	</fakeshop>
	<fakeshop name="Oin" title="Compro Cristais D" classId="11" level="35" x="-14180" y="123340" z="-3115" heading="0" city="Gludio" type="BUY" category="CUSTOM" updateInterval="30" maxItems="4">
		<customitem id="1458" count="500" price="400" />
	</fakeshop>
	<fakeshop name="Gloin" title="Compro Couro e Cord" classId="45" level="35" x="-14130" y="123380" z="-3115" heading="16384" city="Gludio" type="BUY" category="CUSTOM" updateInterval="30" maxItems="4">
		<customitem id="1882" count="100" price="1000" />
		<customitem id="1879" count="100" price="1500" />
	</fakeshop>
	<fakeshop name="Bifur" title="Compro Bones" classId="32" level="35" x="-14260" y="123340" z="-3115" heading="32768" city="Gludio" type="BUY" category="CUSTOM" updateInterval="30" maxItems="4">
		<customitem id="1872" count="100" price="2000" />
	</fakeshop>
	<fakeshop name="Bofur" title="Compro Iron, Bone e Charcoal" classId="54" level="35" x="-14080" y="123445" z="-3115" heading="49152" city="Gludio" type="BUY" category="CUSTOM" updateInterval="30" maxItems="3">
		<customitem id="1869" count="100" price="700" />
		<customitem id="1872" count="100" price="2200" />
		<customitem id="1871" count="100" price="1100" />
	</fakeshop>
	<fakeshop name="Bombur" title="Craft SS C &amp; BSS C" classId="54" level="35" x="-14080" y="123500" z="-3115" heading="0" city="Gludio" type="CRAFT" category="CUSTOM" updateInterval="30" maxItems="2">
		<customitem id="1805" count="1" price="20" />
		<customitem id="1809" count="1" price="40" />
	</fakeshop>
	<fakeshop name="Nori" title="Craft SS D &amp; BSS D (Fee 15a)" classId="56" level="52" x="-14350" y="123550" z="-3115" heading="16384" city="Gludio" type="CRAFT" category="CUSTOM" updateInterval="45" maxItems="2">
		<customitem id="1804" count="1" price="15" />
		<customitem id="1808" count="1" price="25" />
	</fakeshop>
	<fakeshop name="Ori" title="Craft Steel &amp; Cokes (Fee 50a)" classId="56" level="52" x="-14380" y="123500" z="-3115" heading="32768" city="Gludio" type="CRAFT" category="CUSTOM" updateInterval="45" maxItems="2">
		<customitem id="1812" count="1" price="50" />
		<customitem id="1813" count="1" price="50" />
	</fakeshop>
	<fakeshop name="Dori" title="Craft Brigandine &amp; Elven Long" classId="56" level="52" x="-14380" y="123445" z="-3115" heading="49152" city="Gludio" type="CRAFT" category="CUSTOM" updateInterval="45" maxItems="2">
		<customitem id="1815" count="1" price="500" />
		<customitem id="1820" count="1" price="1000" />
	</fakeshop>

</shops>
